---


- name: Install Java 1.8
  apt: name=openjdk-8-jdk state=present

- name: Set JAVA_HOME environment variable
  when: ansible_os_family == 'Ubuntu'
  lineinfile:
    dest='/etc/profile'
    regexp='^#?\s*export JAVA_HOME=(.*)$' line='export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64'
    state=present