---

- name: Install python
  apt:
    name: python
    state: present

- name: Install python3-pip
  apt:
    name: python-pip
    state: present


- name: Install ansible
  pip:
    executable: pip
    name: ansible

- name: Install boto
  pip:
    executable: pip
    name: boto

# - name: Install ansible
#   apt:
#     name: ansible
#     state: present