---

- name: Install python
  apt:
    name: python
    state: present

- name: Install python-pip
  apt:
    name: python-pip
    state: present


- name: Install ansible
  pip:
    executable: pip
    name: ansible

- name: Install boto
  pip:
    executable: pip
    name: boto