---

- name: Install nginx
  apt:
    name=nginx
    state=present

- name: Install apache2-utils
  apt:
    name=apache2-utils
    state=present

- name: Make sure we can use htpasswd module
  apt:
    pkg=python3-passlib
    state=latest
    install_recommends=yes

- name: Ensure htpasswd credentials are configured.
  htpasswd:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('u+rw,g+r') }}"
  with_items: "{{ htpasswd_credentials }}"

- name: Setup Nginx conf
  template:
    src="{{ nginx_conf }}.tpl"
    dest="{{ nginx_path }}/nginx.conf"

- name: Ensure engine conf exists
  template:
    src="{{ site_conf }}.tpl"
    dest="{{ nginx_path }}/conf.d/{{ site_conf }}"
  notify: restart nginx
